export const ESTAMPADOS = [
    "Agua",
    "Aguacates",
    "Aguacatin",
    "Alebrijes",
    "Algodón",
    "Amarillo",
    "Apapacho",
    "Arcoiris",
    "Astronauta",
    "Astronautas",
    "Axolochristmas",
    "Axolote",
    "Axolote Pat",
    "Axolotes",
    "Azul Noche",
    "Bailarinas",
    "Balam",
    "Ballenitas",
    "Blanco",
    "Bombón",
    "Buhos",
    "Buzzi",
    "Calendario",
    "Cactus",
    "Cafe",
    "Cangrejos",
    "Carritos",
    "Cerditos",
    "Cerezul",
    "Chevron",
    "Chicle",
    "Chico",
    "Ciencia",
    "Cocodrilos",
    "Crochet",
    "Cupcakes",
    "Cupcakes Pat",
    "Damask",
    "Dinos",
    "Dinos Chic",
    "Dragones",
    "Eco Revolución",
    "Ecorevolución 2025",
    "Elefantes Azules",
    "Erizos",
    "Estrellas",
    "Estrellas de Mar",
    "Flamingos",
    "Flores Etnicas",
    "Flores Istmo",
    "Floral",
    "Frambuesa",
    "Frosty",
    "Futbol",
    "Gatitos",
    "Girasoles",
    "Grafito",
    "Gris",
    "Hamburguesas",
    "Hippie",
    "Jade",
    "Juguetitos",
    "Jungla",
    "Koala",
    "Koalas",
    "Lila",
    "Lilis",
    "Llamas",
    "Macao",
    "Mandala",
    "Marino",
    "Mezclilla",
    "Menta Limón",
    "Michis",
    "Michis Pat",
    "Minky ¡Jojojojo!",
    "Monster Truck",
    "Monarcas",
    "Mora Azul",
    "Mostaza",
    "Motos",
    "Muñequitas",
    "Nube",
    "Nubes",
    "Ninja",
    "Océano",
    "Pandarina",
    "Pandarinas",
    "Paletitas",
    "Paris",
    "Patitos",
    "Periodico",
    "Pinguinos",
    "Pipo",
    "Pistache",
    "Plumas",
    "Plumitas",
    "Polito",
    "Puppy",
    "Rinos",
    "Robots",
    "Rojo",
    "Rosa",
    "Rudolf",
    "Safari",
    "Sandia",
    "Sandias",
    "Sirenitas",
    "Super Pipo",
    "Surf",
    "Tortulio",
    "Tortulita",
    "Turquesa",
    "Uva",
    "Vainilla",
    "Verano",
    "Verde Limón",
    "Verde Manzana",
    "Verde Primavera",
    "Zarigueya",
    "Zorritos",
    "Aqua",
    "Aviador",
    "Axolotes Pat"
  ]